project_name: dpr_mixcls
device: cuda
dataset_path: ./downloads/data/nq-train
benchmark: true
seed: 42
model:
  tau: 0.07
  mix_layer: 8
  projection: true
train:
  seed: ${seed}
  save_strategy: epoch
  save_total_limit: 1
  learning_rate: 1.0e-05
  optim: adamw_torch_fused
  lr_scheduler_type: linear
  warmup_ratio: 0.1
  max_grad_norm: 2.0
  per_device_train_batch_size: 128
  dataloader_num_workers: 4
  dataloader_persistent_workers: true
  dataloader_pin_memory: true
  dataloader_prefetch_factor: 8
  dataloader_drop_last: true
  num_train_epochs: 30
  logging_steps: 100
  remove_unused_columns: false
  push_to_hub: false
  save_only_model: true
  disable_tqdm: true
