device: cuda
seed: 42
dataset_path: ./downloads/data/nq-train

train:
  save_strategy: epoch
  save_total_limit: 3
  learning_rate: 1e-5
  optim: adamw_torch_fused
  lr_scheduler_type: linear
  warmup_ratio: 0.1
  max_grad_norm: 2.0
  per_device_train_batch_size: 128
  dataloader_num_workers: 4
  dataloader_persistent_workers: True
  dataloader_pin_memory: True
  dataloader_prefetch_factor: 8
  dataloader_drop_last: True
  num_train_epochs: 30
  logging_steps: 100
  remove_unused_columns: False
  push_to_hub: False
  save_only_model: True