device: cuda
seed: 42

train:
  dataset_path: C:\\Users\\iksdg\\dpr\\dpr_base\\downloads\\data\\nq-train
  output_dir: ./output/b32_small_hn
  save_strategy: epoch
  learning_rate: 1e-5
  optim: adamw_torch_fused
  lr_scheduler_type: linear
  warmup_ratio: 0.1
  max_grad_norm: 2.0
  per_device_train_batch_size: 4
  dataloader_num_workers: 4
  dataloader_persistent_workers: True
  dataloader_pin_memory: True
  dataloader_prefetch_factor: 8
  dataloader_drop_last: True
  num_train_epochs: 1
  logging_steps: 100
  remove_unused_columns: False
  push_to_hub: False
  save_only_model: True